import * as THREE from 'three';
const root=document.querySelector('#scene');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let paused=reduced;
const scene=new THREE.Scene();scene.background=new THREE.Color('#15120d');scene.fog=new THREE.FogExp2('#18150f',.023);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,100);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;root.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xa4b1ba,0x3a2310,1.25));scene.add(new THREE.AmbientLight(0xffc989,.65));
const mat=(color,roughness=.8,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness});const brick=mat('#75432e'),stone=mat('#93765a'),gold=mat('#b68b3b',.3,.78),dark=mat('#24251d'),fabric=mat('#dfcbb0'),green=mat('#28482a'),glass=mat('#758a70',.2,.2);
function mesh(geometry,material,x=0,y=0,z=0,parent=scene){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);parent.add(m);return m;}
function box(w,h,d,m,x,y,z,p=scene){return mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,p)}
function cylinder(r,h,m,x,y,z,p=scene){return mesh(new THREE.CylinderGeometry(r,r,h,20),m,x,y,z,p)}
function ball(r,m,x,y,z,p=scene){return mesh(new THREE.SphereGeometry(r,12,8),m,x,y,z,p)}
function curve(points,r,material,parent=scene){return mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),45,r,6,false),material,0,0,0,parent)}
function candle(x,y,z,parent=scene){cylinder(.055,.42,fabric,x,y,z,parent);const flame=mesh(new THREE.SphereGeometry(.055,8,8),new THREE.MeshBasicMaterial({color:0xffd58a}),x,y+.26,z,parent);flame.scale.y=2;return flame;}
// Individual, staggered bricks create the visual frame of the nave.
const dummy=new THREE.Object3D();const brickGeometry=new THREE.BoxGeometry(.68,.28,.27);const bricks=new THREE.InstancedMesh(brickGeometry,brick,2*43*49);let b=0;
for(const side of [-1,1])for(let row=0;row<43;row++)for(let col=0;col<49;col++){dummy.position.set(side*6,row*.30+.15,-17+col*.71+(row%2)*.355);dummy.rotation.set(0,Math.PI/2,0);dummy.updateMatrix();bricks.setMatrixAt(b,dummy.matrix);bricks.setColorAt(b,new THREE.Color().setHSL(.045+Math.random()*.018,.28+Math.random()*.15,.19+Math.random()*.09));b++;}scene.add(bricks);
box(12,.2,35,mat('#463c30'),0,-.12,0);for(let z=-17;z<18;z+=1.5)box(11.9,.012,.015,mat('#9b826055'),0,.001,z);
box(12,13,.5,brick,0,6.5,-17.3);
// Pointed Gothic arches, repeated down the nave; ribs meet above the centre.
for(let z=-15;z<=15;z+=5){for(const side of [-1,1]){cylinder(.24,7.8,stone,side*5.6,3.9,z);box(.8,.3,.8,stone,side*5.6,7.8,z);const pts=[];for(let j=0;j<=24;j++){const t=j/24;pts.push(new THREE.Vector3(side*5.6*(1-t),7.8+5*Math.sin(t*Math.PI/2),z));}curve(pts,.16,stone);curve([new THREE.Vector3(side*5.6,7.8,z),new THREE.Vector3(side*3,11,z+2.5),new THREE.Vector3(0,12.8,z+2.5)],.09,stone);}}
// Ceiling surfaces, intentionally visible in the opening upward view.
for(const side of [-1,1]){const g=new THREE.BufferGeometry();const v=[];for(let j=0;j<24;j++){const t=j/24,u=(j+1)/24;const x=side*5.6*(1-t),xx=side*5.6*(1-u),y=7.8+5*Math.sin(t*Math.PI/2),yy=7.8+5*Math.sin(u*Math.PI/2);v.push(x,y,-17,xx,yy,-17,x,y,18,xx,yy,-17,xx,yy,18,x,y,18);}g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.computeVertexNormals();const roof=mat('#543b2d');roof.side=THREE.DoubleSide;mesh(g,roof);}
// Stained glass rose over the altar.
const rose=new THREE.Group();rose.position.set(0,9.1,-16.99);scene.add(rose);mesh(new THREE.TorusGeometry(2.15,.13,12,64),stone,0,0,0,rose);const colors=['#ae604b','#536e90','#c39e49','#61775b','#784b71'];for(let k=0;k<12;k++){const a=k*Math.PI/6;const pane=mesh(new THREE.CircleGeometry(.58,24),new THREE.MeshBasicMaterial({color:colors[k%5]}),Math.cos(a)*1.32,Math.sin(a)*1.32,0,rose);mesh(new THREE.TorusGeometry(.6,.05,6,30),gold,pane.position.x,pane.position.y,.03,rose);curve([new THREE.Vector3(0,0,.06),new THREE.Vector3(Math.cos(a)*2.1,Math.sin(a)*2.1,.06)],.035,stone,rose);}mesh(new THREE.CircleGeometry(.61,30),new THREE.MeshBasicMaterial({color:'#d7b775'}),0,0,.07,rose);mesh(new THREE.TorusGeometry(.65,.06,8,36),gold,0,0,.08,rose);
for(const side of [-1,1])for(let z=-12;z<=12;z+=6){const window=new THREE.Group();window.position.set(side*5.82,6.2,z);window.rotation.y=side*Math.PI/2;scene.add(window);for(let i=0;i<3;i++)box(.55,3,.04,new THREE.MeshBasicMaterial({color:colors[(i+Math.round(z+12))%5]}),(i-1)*.6,0,0,window);for(let i=0;i<4;i++)box(.035,3.2,.06,stone,(i-1.5)*.6,0,.03,window);const light=new THREE.PointLight(colors[Math.abs(z)%5],5,9);light.position.set(side*4.8,5,z);scene.add(light);}
// The chandelier is actual geometry: two brass crowns, curved arms and candles.
const chandelier=new THREE.Group();chandelier.position.set(0,8.1,3);scene.add(chandelier);cylinder(.045,4.4,gold,0,2.2,0,chandelier);ball(.25,gold,0,0,0,chandelier);
for(const [r,y,count] of [[2.2,0,18],[1.25,1.15,12]]){const ring=mesh(new THREE.TorusGeometry(r,.065,10,80),gold,0,y,0,chandelier);ring.rotation.x=Math.PI/2;for(let k=0;k<count;k++){const a=k/count*Math.PI*2;const x=Math.cos(a)*r,z=Math.sin(a)*r;curve([new THREE.Vector3(0,y+.7,0),new THREE.Vector3(x*.5,y-.3,z*.5),new THREE.Vector3(x,y,z)],.045,gold,chandelier);cylinder(.14,.08,gold,x,y+.07,z,chandelier);candle(x,y+.32,z,chandelier);for(let q=0;q<3;q++){const crystal=mesh(new THREE.OctahedronGeometry(.07),glass,x*.95,y-.18-q*.14,z*.95,chandelier);crystal.scale.y=1.8;}}}
const glow=new THREE.PointLight(0xffbd65,55,20,2);glow.position.set(0,8,3);scene.add(glow);
// Intimate tables, velvet seating, glassware, plants and altar kitchen.
function table(x,z){cylinder(.09,1.0,gold,x,.5,z);cylinder(1.05,.08,fabric,x,1.05,z);for(let k=0;k<3;k++){const a=k*2*Math.PI/3;const px=x+Math.cos(a)*.65,pz=z+Math.sin(a)*.65;cylinder(.2,.025,mat('#f1e7cf'),px,1.11,pz);cylinder(.035,.20,gold,px+.2,1.2,pz);ball(.08,glass,px+.2,1.34,pz);const cx=x+Math.cos(a)*1.35,cz=z+Math.sin(a)*1.35;cylinder(.38,.13,mat('#64382e'),cx,.57,cz);const back=box(.7,.65,.12,mat('#64382e'),cx,.95,cz);back.rotation.y=-a+Math.PI/2;for(const s of [-1,1])cylinder(.025,.55,gold,cx+s*.24,.27,cz);}candle(x,1.35,z);const l=new THREE.PointLight(0xffb75e,2.5,3);l.position.set(x,1.6,z);scene.add(l);}
for(const z of [-8,-2,5,11])for(const side of [-1,1])table(side*3.5,z);
function plant(x,z){cylinder(.42,.7,mat('#654e30'),x,.35,z);for(let k=0;k<12;k++){const a=k*2.4,r=.35+Math.random()*.5,h=1+Math.random()*1.7;curve([new THREE.Vector3(x,.65,z),new THREE.Vector3(x+Math.cos(a)*r,h,z+Math.sin(a)*r)],.018,green);const leaf=mesh(new THREE.SphereGeometry(.25,8,6),green,x+Math.cos(a)*r,h,z+Math.sin(a)*r);leaf.scale.set(.5,2.1,1);leaf.rotation.z=Math.cos(a)*.7;}}for(const z of [-13,-5,3,13])for(const side of [-1,1])plant(side*5,z);
box(9,.3,4,stone,0,.15,-14.5);box(7,1.15,1.3,mat('#544e42'),0,.9,-14.5);box(7.2,.12,1.5,mat('#a69b7d',.3,.6),0,1.53,-14.5);for(let x=-2;x<=2;x+=2){cylinder(.28,.18,mat('#272821',.2,.7),x,1.66,-14.5);cylinder(.027,2,gold,x,2.6,-14.8);const shade=mesh(new THREE.ConeGeometry(.45,.28,20,1,true),gold,x,3.6,-14.5);shade.rotation.x=Math.PI;const l=new THREE.PointLight(0xffc777,6,5);l.position.set(x,3,-14.5);scene.add(l);}
// Dust catches the light. Its subtle motion stops with the accessibility control.
const positions=new Float32Array(240*3);for(let i=0;i<positions.length;i+=3){positions[i]=(Math.random()-.5)*11;positions[i+1]=Math.random()*12;positions[i+2]=(Math.random()-.5)*30;}const particlesGeometry=new THREE.BufferGeometry();particlesGeometry.setAttribute('position',new THREE.BufferAttribute(positions,3));const dust=new THREE.Points(particlesGeometry,new THREE.PointsMaterial({color:'#c5ac79',size:.025,transparent:true,opacity:.45}));scene.add(dust);
const keys=[{p:0,pos:[0,3.3,3],look:[0,10,3.01],roll:-.45},{p:.20,pos:[.9,4,7],look:[0,8,2],roll:.22},{p:.43,pos:[0,2.8,13],look:[0,4,-12],roll:0},{p:.72,pos:[-.8,2.4,1],look:[0,2,-14.5],roll:0},{p:1,pos:[0,2.1,-7],look:[0,2,-14.5],roll:0}];
let target=0,current=0;const look=new THREE.Vector3();const clock=new THREE.Clock();let previousTime=0;function updateTarget(){target=Math.min(1,scrollY/(document.documentElement.scrollHeight-innerHeight));document.querySelector('#progress-fill').style.height=`${target*100}%`;document.querySelector('#chapter-number').textContent=String(Math.min(4,Math.floor(target*4)+1)).padStart(2,'0');}addEventListener('scroll',updateTarget,{passive:true});updateTarget();
function render(){requestAnimationFrame(render);const time=clock.getElapsedTime();const dt=Math.min(time-previousTime,.3);previousTime=time;current+=(target-current)*(paused?1:1-Math.exp(-dt*6));let a=keys[0],b=keys[1];for(let i=0;i<keys.length-1;i++)if(current>=keys[i].p){a=keys[i];b=keys[i+1];}let t=THREE.MathUtils.clamp((current-a.p)/(b.p-a.p),0,1);t=t*t*(3-2*t);camera.position.fromArray(a.pos).lerp(new THREE.Vector3(...b.pos),t);look.fromArray(a.look).lerp(new THREE.Vector3(...b.look),t);camera.up.set(Math.sin(THREE.MathUtils.lerp(a.roll,b.roll,t)),Math.cos(THREE.MathUtils.lerp(a.roll,b.roll,t)),0);camera.lookAt(look);if(!paused){chandelier.rotation.y=Math.sin(time*.15)*.055;dust.rotation.y=time*.006;glow.intensity=55+Math.sin(time*2)*2;}renderer.render(scene,camera);}render();document.querySelector('#loading').classList.add('done');
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);updateTarget();});
const motion=document.querySelector('#motion');function motionLabel(){motion.textContent=paused?'Riprendi movimento':'Pausa movimento';motion.setAttribute('aria-pressed',String(paused));}motionLabel();motion.addEventListener('click',()=>{paused=!paused;motionLabel();});
const booking=document.querySelector('#booking');document.querySelectorAll('[data-book]').forEach(b=>b.addEventListener('click',()=>booking.showModal()));document.querySelector('#menu-button').addEventListener('click',()=>document.querySelector('#menu').showModal());document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});const today=new Date();document.querySelector('#date').min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;document.querySelector('#booking-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);const message=document.querySelector('#confirmation');message.textContent=`${data.get('name')}, la tua richiesta per ${data.get('guests')} il ${new Date(data.get('date')+'T12:00:00').toLocaleDateString('it-IT')} è pronta. Questa è una dimostrazione: nessun tavolo è stato prenotato. Il servizio di prenotazione deve ancora essere collegato.`;message.hidden=false;e.target.hidden=true;});
