const root=document.querySelector('#scene');
const motionPreference=matchMedia('(prefers-reduced-motion: reduce)');
const reduced=motionPreference.matches;
let paused=reduced;
root.innerHTML=`<div class="photo-stage"><div class="room-shot"><img src="/images/room.webp" alt="Santa Cecilia: sala gotica in mattoni vissuti, tavoli intimi e cucina sull’altare" fetchpriority="high"></div><div class="ceiling-shot"><img src="/images/ceiling.webp" alt="Vista dal basso del candelabro in ottone sotto le volte gotiche" fetchpriority="high"></div><div class="light-breath"></div><div class="dust-layer" aria-hidden="true"></div></div>`;
const stage=root.querySelector('.photo-stage'),room=root.querySelector('.room-shot'),ceiling=root.querySelector('.ceiling-shot');
const smooth=(a,b,x)=>{const t=Math.max(0,Math.min(1,(x-a)/(b-a)));return t*t*(3-2*t);};
let target=0,current=0,last=performance.now(),elapsed=0,pointerX=0,pointerY=0,spatial;
function updateTarget(){const range=document.querySelector('#racconto').offsetTop;document.body.classList.toggle('reading',scrollY>=range-120);target=range>0?Math.min(1,Math.max(0,scrollY/range)):0;document.querySelector('#progress-fill').style.height=`${target*100}%`;document.querySelector('#chapter-number').textContent=String(Math.min(4,Math.floor(target*4)+1)).padStart(2,'0');}
addEventListener('scroll',updateTarget,{passive:true});addEventListener('resize',updateTarget);updateTarget();
addEventListener('pointermove',e=>{if(e.pointerType==='mouse'){pointerX=(e.clientX/innerWidth-.5)*2;pointerY=(e.clientY/innerHeight-.5)*2;}},{passive:true});
function animate(now){const dt=Math.min((now-last)/1000,.1);last=now;if(!paused)elapsed+=dt;current+=(target-current)*(paused?1:1-Math.exp(-dt*7));const descent=paused?0:smooth(.04,.37,current),reveal=paused?(target>.17?1:0):smooth(.17,.36,current),approach=paused?0:smooth(.40,.92,current);const sway=paused?0:Math.sin(elapsed*.22)*.35;const px=paused?0:pointerX*5,py=paused?0:pointerY*3;
ceiling.style.transform=`translate3d(${px}px,${descent*-8}%,0) rotate(${(paused?0:-17+descent*27+sway).toFixed(3)}deg) scale(${1.24+descent*.23})`;ceiling.style.opacity=String(1-reveal);
room.style.transform=`translate3d(${-px*.6}px,${4-descent*4+approach*8}%,0) scale(${1.09+approach*.36})`;room.style.opacity=String(reveal);stage.style.setProperty('--breath',paused?'0.025':String(.025+Math.sin(elapsed*.7)*.012));stage.style.setProperty('--pointer-y',`${py}px`);requestAnimationFrame(animate);}requestAnimationFrame(animate);
function setMotion(){const motion=document.querySelector('#motion');motion.textContent=paused?'Riprendi movimento':'Pausa movimento';motion.setAttribute('aria-pressed',String(paused));stage.classList.toggle('paused',paused);spatial?.setPaused(paused);}setMotion();motionPreference.addEventListener('change',event=>{paused=event.matches;setMotion();});document.querySelector('#motion').addEventListener('click',()=>{paused=!paused;setMotion();});
const images=[...root.querySelectorAll('img')];Promise.all(images.map(img=>img.decode())).then(()=>document.querySelector('#loading').classList.add('done')).catch(async()=>{root.innerHTML='';try{const {mountSpatialScene}=await import('./scene-model.js');spatial=mountSpatialScene();spatial.setPaused(paused);}catch{root.innerHTML='<div class="scene-unavailable">La scena non è disponibile. Puoi continuare a leggere e consultare il menu.</div>';}document.querySelector('#loading').classList.add('done');});
const occasion=document.querySelector('#occasion');
function updateOccasion(){document.querySelector('#notes-label').firstChild.textContent=occasion.value==='event'?'Raccontaci il tuo evento':'Preferenze o richieste particolari';document.querySelector('#booking-intro').textContent=occasion.value==='event'?'Indicaci la data, gli ospiti e l’occasione: immaginiamo insieme la tua serata.':'Scegli la data e il numero di ospiti per la tua cena.';}
occasion.addEventListener('change',updateOccasion);
const booking=document.querySelector('#booking');document.querySelectorAll('[data-book]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#booking-form').hidden=false;document.querySelector('#confirmation').hidden=true;document.querySelector('#occasion').value=b.dataset.book==='event'?'event':'dinner';updateOccasion();booking.showModal();}));document.querySelector('#menu-button').addEventListener('click',()=>document.querySelector('#menu').showModal());document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});const today=new Date();document.querySelector('#date').min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;document.querySelector('#booking-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);const message=document.querySelector('#confirmation');message.textContent=`${data.get('name')}, la tua richiesta ${data.get('occasion')==='event'?'per un evento':'per una cena'} con ${data.get('guests')} ospiti il ${new Date(data.get('date')+'T12:00:00').toLocaleDateString('it-IT')} è pronta. Questa è una dimostrazione: la richiesta non è stata inviata e nessuna disponibilità è confermata. Il servizio di prenotazione deve ancora essere collegato.`;message.hidden=false;e.target.hidden=true;message.focus();});
